require:
  - rubocop-rails
  - rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'bundle/**/*' # Add this line if using Bundler
    - 'node_modules/**/*' # If you have a Node.js environment

# Caveat: .find_by raises exception in mongoid, unlike ActiveRecord which
# returns nil
Rails/FindBy:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods # Updated cop style

Style/GuardClause:
  MinBodyLength: 4

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/SpaceAroundOperators:
  AllowForAlignment: true

# long spec blocks are probably fine
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context'] # Updated cop name

Naming/FileName:
  Exclude:
    - 'config/initializers/cve-*.rb'
