version: "3"

services:
  errbit:
    restart: always
    image: clearstackio/errbit:0.9.1
    ports:
      - "8080:8080"
    depends_on:
      - errbit_mongo
    environment:
      - PORT=8080
      - RACK_ENV=production
      - MONGO_URL=mongodb://errbit_mongo:27017/errbit
  errbit_mongo:
    restart: always
    image: mongo:7.0.11
    volumes:
      - errbit_mongo_data:/data/db
    ports:
      - "27017"
volumes:
  errbit_mongo_data:
